Repository Canardoux/tau, pull requests merged in 2020-01, with the labels that each got.

#179 Android minSdkVersion is 22 instead of 23. SDK before 22 fails
  android/build.gradle
  example/android/app/build.gradle
Labels: enhancement, environment

#177 Fix for Bug #128
  lib/flutter_sound.dart
Labels: bugfix

#185 Compatibility with Android SDK 19
  android/build.gradle
  android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
  example/android/app/build.gradle
  example/ios/Runner.xcodeproj/project.pbxproj
  example/lib/generated/json/base/json_convert_content.dart
  example/lib/generated/json/base/json_filed.dart
  ios/Classes/FlutterSoundPlugin.m
  lib/flutter_sound.dart
Labels: enhancement

#199 OGG/OPUS support on iOS
  README.md
  android/build.gradle
  android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
  example/.flutter-plugins-dependencies
  example/android/app/build.gradle
  example/ios/Podfile
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  example/lib/main.dart
  example/pubspec.yaml
  ios/Classes/FlutterSoundPlugin.m
  lib/flutter_sound.dart
  pubspec.yaml
Labels: enhancement, feature
