Repository Canardoux/tau, pull requests merged in 2020-02, with the labels that each got.

#211 Release 2.0.4
  .gitignore
  CHANGELOG.md
  example/.flutter-plugins-dependencies
  lib/flutter_sound.dart
  pubspec.yaml
Labels: release

#209 Use AAC-LC format instead of MPEG-4
  android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
Labels: enhancement

#224 Fix android path to be appended
  android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
  example/lib/main.dart
Labels: bugfix

#225 Enh/custom path handling
  CHANGELOG.md
  README.md
  android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
  example/lib/main.dart
  example/pubspec.yaml
  lib/flutter_sound.dart
  pubspec.yaml
Labels: enhancement
